name: 'Volcado y restauración de RDS'
description: 'Volcado y restauración de MySQL/MariaDB RDS a través de Secrets Manager y S3'
author: 'Orencio Ramirez'
inputs:
  mode:
    description: 'Modo de operación: extraer | restaurar | completo'
    required: true
  aws_account_origin:
    description: 'ID de cuenta AWS de origen (para extraer o completo)'
    required: false
  secret_origin:
    description: 'Nombre del secreto de origen en AWS Secrets Manager'
    required: false
  aws_account_dest:
    description: 'ID de cuenta AWS de destino (para restaurar o completo)'
    required: false
  secret_dest:
    description: 'Nombre del secreto de destino en AWS Secrets Manager'
    required: false
  presigned_url:
    description: 'URL pre-firmada S3 (necesaria en modo restaurar)'
    required: false
  ttl:
    description: 'TTL de la URL pre-firmada en segundos'
    required: false
    default: '7200'
outputs:
  presigned_url:
    description: "URL pre-firmada generada tras el volcado"
    value: ${{ steps.run_script.outputs.presigned_url }}

runs:
  using: "composite"
  steps:
    - name: Instalar Dependencias
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y awscli jq mysql-client gzip curl

    - name: Ejecutar Volcado y restauración de RDS
      id: run_script
      shell: bash
      run: |
        chmod +x ${{ github.action_path }}/entrypoint.sh
        case "${{ inputs.mode }}" in
          extraer)
            ${{ github.action_path }}/entrypoint.sh extraer \
              "${{ inputs.aws_account_origin }}" \
              "${{ inputs.secret_origin }}" \
              "${{ inputs.ttl }}"
            ;;
          restaurar)
            ${{ github.action_path }}/entrypoint.sh restaurar \
              "${{ inputs.aws_account_dest }}" \
              "${{ inputs.secret_dest }}" \
              "${{ inputs.presigned_url }}"
            ;;
          completo)
            ${{ github.action_path }}/entrypoint.sh completo \
              "${{ inputs.aws_account_origin }}" \
              "${{ inputs.secret_origin }}" \
              "${{ inputs.aws_account_dest }}" \
              "${{ inputs.secret_dest }}" \
              "${{ inputs.ttl }}"
            ;;
          *)
            echo "Modo no soportado: ${{ inputs.mode }}"
            exit 1
            ;;
        esac
