name: Github Action para volcado y restauraci贸n de RDS MySQL/MariaDB en Griddo
description: Volcado y restauraci贸n de RDS MySQL/MariaDB con AWS, S3 y Secrets Manager.
author: Orencio
inputs:
  mode:
    description: Modo de operaci贸n extraer, restaurar, completo
    required: true
  aws_account_id_origen:
    description: Cuenta AWS origen (dump)
    required: false
  secreto_origen:
    description: Nombre del secreto en origen
    required: false
  aws_account_id_destino:
    description: Cuenta AWS destino (restaurar)
    required: false
  secreto_destino:
    description: Nombre del secreto en destino
    required: false
  ttl:
    description: Tiempo de vida en segundos del presigned URL
    required: false
    default: "7200"
  url_presigned:
    description: URL presignada S3 para restauraci贸n
    required: false

runs:
  using: "composite"
  steps:
    - run: bash "${{ github.action_path }}/entrypoint.sh"
      shell: bash
      env:
        MODE: "${{ inputs.mode }}"
        AWS_ACCOUNT_ID_ORIGEN: "${{ inputs.aws_account_id_origen }}"
        SECRETO_ORIGEN: "${{ inputs.secreto_origen }}"
        AWS_ACCOUNT_ID_DESTINO: "${{ inputs.aws_account_id_destino }}"
        SECRETO_DESTINO: "${{ inputs.secreto_destino }}"
        TTL: "${{ inputs.ttl }}"
        URL_PRESIGNED: "${{ inputs.url_presigned }}"
