name: "AWS RDS Dump & Restore"
description: "Vuelca, comprime, sube, descarga y restaura bases de datos RDS MySQL/MariaDB en AWS, con filtrado de datos sensibles."
author: "Tu nombre o tu organización"
inputs:
  mode:
    description: "Modo de operación: extraer | restaurar | completo"
    required: true
  aws_account_id_origen:
    description: "AWS Account ID origen (para extraer o completo)"
    required: false
  aws_account_id_destino:
    description: "AWS Account ID destino (para restaurar o completo)"
    required: false
  secreto_origen:
    description: "Nombre del secreto origen en AWS Secrets Manager"
    required: false
  secreto_destino:
    description: "Nombre del secreto destino en AWS Secrets Manager"
    required: false
  ttl:
    description: "Tiempo de vida del presigned URL en segundos"
    required: false
    default: "7200"
  presigned_url:
    description: "URL presignada de S3 (para restaurar)"
    required: false

runs:
  using: "composite"
  steps:
    - name: Configurar permisos de ejecución
      shell: bash
      run: chmod +x ${{ github.action_path }}/entrypoint.sh
    - name: Ejecutar Script
      shell: bash
      run: |
        ${{ github.action_path }}/entrypoint.sh \
          "${{ inputs.mode }}" \
          "${{ inputs.aws_account_id_origen }}" \
          "${{ inputs.secreto_origen }}" \
          "${{ inputs.aws_account_id_destino }}" \
          "${{ inputs.secreto_destino }}" \
          "${{ inputs.presigned_url }}" \
          "${{ inputs.ttl }}"
